### ISSUE TITLE
finansbank yeni sanal pos

### ISSUE THREAD

**Issue by tughann** [sefacan/3DPaymentAspNetCore#1]
Merhabalar, finansbank yeni bir sanal pos sistemine geçmiş, buradaki kodlar eski sanal posa göre mi acaba?

**Comment by sefacan** [comment]
Merhaba,
Yeni altyapı entegrasyonunu henüz deneyimlemedim. Bunun için elinizde döküman mevcut mu?

**Comment by sefacan** [comment]
@tughann gerekli dökumanları bulup entegrasyonu yaptım. 
https://github.com/sefacan/3DPaymentAspNetCore/commit/a96ab5c932dd4098d35fc40ee0d167776aee4bd2

**Comment by tughann** [comment]
Teşekkür ederim elinize sağlık, yenisine uyarlamıştım ben de ama sonra burayı kontrol etmeyi unutmuşum.
