### ISSUE TITLE
Kart Bilgilerini girip gönder dediğimde hiç bir uyarı veya işlem olmuyor.

### ISSUE THREAD

**Issue by sebahattinkoc** [sefacan/3DPaymentAspNetCore#10]
Sorun nerede olabilir acaba ? tşk.ler.

**Comment by sebahattinkoc** [comment]
Index.cshtml dosyasında asp-controller="Home" 'u asp-controller="Payment" yapınca sorun çözüldü

**Comment by sefacan** [comment]
Merhaba,
Sample projede eksikler mevcut. Projede geliştirilmesi gereken bir çok nokta var bu yüzden katkıda bulunarak pull-request gönderirseniz birlikte sorunları giderip daha iyi hale getirebiliriz.

Teşekkürler.
