### ISSUE TITLE
Web uygulaması hataları.

### ISSUE THREAD

**Issue by leventsumaksau** [sefacan/3DPaymentAspNetCore#12]
Merhabalar. Elinize sağlık.

Sample projesindeki hatalar çok fazla ve işleyişi tam olarak bilmediğim için müdahale edemiyorum.
O kısımlar için yapabileceğiniz bir şey var mıdır?

**Comment by sefacan** [comment]
Merhaba,
Yakın zamanda daha gelişmiş bir örnek proje oluşturacağım.

Teşekkürler.

**Comment by fetullahyldz** [comment]
Merhaba  Sadece yapıkredi için çalışmanız varmı

**Comment by sefacan** [comment]
@fetullahyldz merhaba proje kodları içerisinde Yapikredi entegrasyonu mevcut.

**Comment by fetullahyldz** [comment]
Evet Denedim Ama Çalışmadı Galiba Sorun Yapı kredi kaynaklı sürekli ip değişiyor ve çok uğraştırıyor.

**Comment by sefacan** [comment]
Öncelikle local ortamda bankadan alacağınız test bilgileriyle başarılı işlem geçmeniz ve sonrasında canlı bilgilerini bankadan isteyip canlı ortamda 1 liralık gerçek işlem geçin. Tabi canlıya geçerken sunucu ip adresini mutlaka bankaya iletin. Bazı bankalarda ip kısıtlaması varken bazılarında böyle bir sorun yok.

**Comment by fetullahyldz** [comment]
Localde de ip hatası veriyor  ben Nopcommerce için sadece yapı kredi bankası için  modül oluşturdum  tabi nopcommerce xml serialize etmiyor o yüzden biraz farklı metod denedim ancak sürekli ip hatalı görüştüm banka tarfıyla ordaki destek veren arkaş çok kafa karştıryor. ilerliyemedik bir türlü yapı kredi 3 defa istek yaptırıyor .

**Comment by fetullahyldz** [comment]
Merhaba Localde Test Etiğimde Hata Alıyorum 

System.AggregateException
  HResult=0x80131500
  İleti=One or more errors occurred. (Bilinen böyle bir ana bilgisayar yok)
  Kaynak=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) in C:\A\1\11\s\src\mscorlib\src\System\Threading\Tasks\future.cs:line 498
   at Nop.Plugin.Payments.ThreeDPayment.ThreeDPaymentPaymentProcessor.<ThreeDGatewayRequest>d__16.MoveNext() in C:\Users\Fatih\Desktop\New-NopCommerce_4.10_\Plugins\Nop.Plugin.Payments.ThreeDPayment\ThreeDPaymentPaymentProcessor.cs:line 218
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in C:\A\1\11\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in C:\A\1\11\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in C:\A\1\11\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 376
   at Nop.Plugin.Payments.ThreeDPayment.ThreeDPaymentPaymentProcessor.<PostProcessPayment>d__15.MoveNext() in C:\Users\Fatih\Desktop\New-NopCommerce_4.10_\Plugins\Nop.Plugin.Payments.ThreeDPayment\ThreeDPaymentPaymentProcessor.cs:line 157
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in C:\A\1\11\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in C:\A\1\11\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 167
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in C:\A\1\11\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in C:\A\1\11\s\src\mscorlib\src\System\Threading\ThreadPool.cs:line 588

İçteki Özel Durum 1:
HttpRequestException: Bilinen böyle bir ana bilgisayar yok

İçteki Özel Durum 2:
SocketException: Bilinen böyle bir ana bilgisayar yok

**Comment by sefacan** [comment]
Merhaba,
Projede bir bağlantı yapmaya çalışıyor fakat adres geçersiz görünüyor.

**Comment by fetullahyldz** [comment]
Sizin istek yapınız 3DS' mi.   3DS istek için sanal postn 3Ds tanımımı olmalıdır.

**Comment by fetullahyldz** [comment]
public string CreatePaymentFormHtml(IDictionary<string, object> parameters, Uri actionUrl, bool appendSubmitScript = true)
        {
            if (parameters == null || !parameters.Any())
                throw new ArgumentNullException(nameof(parameters));

            if (actionUrl == null)
                throw new ArgumentNullException(nameof(actionUrl));

            var formId = "PaymentForm";
            var formBuilder = new StringBuilder();
            formBuilder.Append($"<form id=\"{formId}\" name=\"{formId}\" action=\"{actionUrl}\" role=\"form\" method=\"POST\">");

            foreach (var parameter in parameters)
            {
                formBuilder.Append($"<input type=\"hidden\" name=\"{parameter.Key}\" value=\"{parameter.Value}\">");
            }

            formBuilder.Append("</form>");

            if (appendSubmitScript)
            {
                var scriptBuilder = new StringBuilder();
                scriptBuilder.Append("<script>");
                scriptBuilder.Append($"document.{formId}.submit();");
                scriptBuilder.Append("</script>");
                formBuilder.Append(scriptBuilder.ToString());
            }

            return formBuilder.ToString();
        }


BURAYA DEBUG ETİĞİMDE DEĞERLER NULL GELİYOR VE O YÜZDEN HATA VERİYOR LÜTFEN BAKARMISINIZ YAPI KREDİ İÇİN

**Comment by fetullahyldz** [comment]
Merhaba Sonunda Bankaya Giti ancak forum alnında CallbackUrl geri dönmüyor direk sipariş tamamlandı kısmına düşüyor 3d şifre doğrulama ekranı gelmiyor

**Comment by fetullahyldz** [comment]
var paymentForm = _paymentProviderFactory.CreatePaymentFormHtml(paymentGatewayResult.Parameters, paymentGatewayResult.GatewayUrl);   bu kısmda datallar geliyor ancak dediğim gibi  CallbackUrl  urleyde gitmiyor 3d ekran açılmıyor

**Comment by sefacan** [comment]
Bazı bankaların test ortamında sms sayfası açılmayıp başarılı sayfasına yönlendirme yapıyor. Bu sebepten dolayı olabilir. Size dönen değerleri kontrol ettiğinizde başarılı ise canlıda da aynı şekilde çalışacak demektir.

**Comment by fetullahyldz** [comment]
Anladım Yarın Test Edeceğim İp Değiştiği İçin şuan test yapmadım  canlıda sms sayfası açılacak yani  sms için bankanın ortak sms sayfasınmı gidecek yoksa popup şeklindemi açılacak

**Comment by fetullahyldz** [comment]
{<form id="PaymentForm" name="PaymentForm" action="https://setmpos.ykb.com/3DSWebService/YKBPaymentService" role="form" method="POST"><input type="hidden" name="posnetData" value="E8546AEA4B3852D2C62E655502B9F50B12DAA169E50ECDC025ED4C444C5C29B822D89B76D2453EE945F6418AF1DC19F8A75146176ECFC0D1559DED920F9814F372A5FB96CA3E22E1AC49C56046619A542967E184EBC6A10136ABC80D4D667B160F0929FA0934C08531D16D5AF77D2BF79B0473ADBFAAE26B66486CF5B88F32217F9C8E53CF5CE7F0D5449529E6BFA0B3C25C06F29F8652BA753FB3E0F0B7CE9E3ABA884E7D28A3AD2F79D946"><input type="hidden" name="posnetData2" value="8ABED90EAA23A59479F7EB744CC9ECC633F17D2DEEC24BBC9E373F240891149F5478C1ABFABAD70DAE23ADE9465FDA839D1FDC579DD1EFD89D370C46"><input type="hidden" name="digest" value="6439EAD90FD7D8D5090B198DDED20290"><input type="hidden" name="mid" value="6700972634"><input type="hidden" name="posnetID" value="1010052104940374"><input type="hidden" name="vftCode" value=""><input type="hidden" name="merchantReturnURL" value="http://localhost:15536/Plugins/PaymentThreeDPayment/Callback"><input type="hidden" name="lang" value="tr"><input type="hidden" name="url" value=""><input type="hidden" name="openANewWindow" value="0"><input type="hidden" name="useJokerVadaa" value="1"></form><script>document.PaymentForm.submit();</script>}



Bu Şekilde Forum Alıyorum ama post etmiyor burda bankaya Neden olabilir.

**Comment by fetullahyldz** [comment]
{<form id="PaymentForm" name="PaymentForm" action="https://setmpos.ykb.com/3DSWebService/YKBPaymentService" role="form" method="POST"><input type="hidden" name="posnetData" value="E8546AEA4B3852D2C62E655502B9F50B12DAA169E50ECDC025ED4C444C5C29B822D89B76D2453EE945F6418AF1DC19F8A75146176ECFC0D1559DED920F9814F372A5FB96CA3E22E1AC49C56046619A542967E184EBC6A10136ABC80D4D667B160F0929FA0934C08531D16D5AF77D2BF79B0473ADBFAAE26B66486CF5B88F32217F9C8E53CF5CE7F0D5449529E6BFA0B3C25C06F29F8652BA753FB3E0F0B7CE9E3ABA884E7D28A3AD2F79D946"><input type="hidden" name="posnetData2" value="8ABED90EAA23A59479F7EB744CC9ECC633F17D2DEEC24BBC9E373F240891149F5478C1ABFABAD70DAE23ADE9465FDA839D1FDC579DD1EFD89D370C46"><input type="hidden" name="digest" value="6439EAD90FD7D8D5090B198DDED20290"><input type="hidden" name="mid" value="6700972634"><input type="hidden" name="posnetID" value="1010052104940374"><input type="hidden" name="vftCode" value=""><input type="hidden" name="merchantReturnURL" value="http://localhost:15536/Plugins/PaymentThreeDPayment/Callback"><input type="hidden" name="lang" value="tr"><input type="hidden" name="url" value=""><input type="hidden" name="openANewWindow" value="0"><input type="hidden" name="useJokerVadaa" value="1"></form><script>document.PaymentForm.submit();</script>}


Bu Şekilde Forum Alıyorum ama post etmiyor burda bankaya Neden olabilir.

**Comment by fetullahyldz** [comment]
CreatePaymentFormHtml buraya datalar geliyor ama forumu post etmiyor bunun yapan javascriptmi var anlamadım

**Comment by ouzdev** [comment]
Sanırım javascript var entegrasyon dokumanı içerisinde bu şekilde bir ibare mevcut.

**Comment by ouzdev** [comment]
Bende Nop Commerce'e Yapı Kredi için eklenti yazacağım sanırım baya bi uğraşacağız.

**Comment by sefacan** [comment]
Javascript ile ekstra birşey yazmanız gerekmiyor aslında. Sayfa yönlendirmesi yapmak veya Modal olarak açmak sizin tercihiniz.

**Comment by fetullahyldz** [comment]
kadar datalar geliyor ama burdan sonra bankaya post işlemi olmuyor 2 haftadır banka ile birlikte işlem yapıyorum herşey tamam ama bankaya gitmiyor. 

 var ForumPost = CreatePaymentFormHtml(paymentGatewayResult.Parameters, paymentGatewayResult.GatewayUrl);  Buraya 
            _httpContext.HttpContext.Response.Redirect(ForumPost);

**Comment by fetullahyldz** [comment]
Buraya kadar datalar geliyor ama buradan sonra bankaya post işlemi olmuyor 2 haftadır banka ile birlikte işlem yapıyorum her şey tamam ama bankaya gitmiyor.

var ForumPost = CreatePaymentFormHtml(paymentGatewayResult.Parameters, paymentGatewayResult.GatewayUrl); 
_httpContext.HttpContext.Response.Redirect(ForumPost);

**Comment by sefacan** [comment]
Html olarak dönen veriyi redirect edemezsiniz. Örnek projeyi incelerseniz, onu model olarak view'a gönderip html olarak sayfaya basıyorum ve formu javascript ile otomatik submit ediyorum.

**Comment by sefacan** [comment]
@fetullahyldz 
Aşağıdaki satırları incelemenizi öneririm.
[PaymentController.cs#L87](https://github.com/sefacan/3DPaymentAspNetCore/blob/master/samples/ThreeDPayment.Sample/Controllers/PaymentController.cs#L87)
[ThreeDGate.cshtml#L14](https://github.com/sefacan/3DPaymentAspNetCore/blob/master/samples/ThreeDPayment.Sample/Views/Payment/ThreeDGate.cshtml#L14)

**Comment by fetullahyldz** [comment]
Zaten Buna Göre ilerleme yapıyorum  return View(model: paymentForm); burda view kısmınada vermişsiniz  geri dönüş olarak yani nasıl bankaya gidecek

**Comment by fetullahyldz** [comment]
"<?xml version='1.0' encoding='iso-8859-9'?><posnetResponse><approved>1</approved><oosRequestDataResponse><data1>D41B6A08198CE1D0C3D34D60F60E2B798C3DB49969D9685432311A17BA2016264929462932BF8CFFE41CC18A890AA6EB881E38C917F7B82793438369DA7B96F7E5A64412E0F83A9ADAFA5C795293100FEB4AF80F19C89EFC0790A0C41ED4CF107FA019D85A8F346EEA79B6FF5EDF18879E7BE1CDE3F9298B58DDDC190E5891F76EC5479C311A3531718CD7CEE0995594B9804F6EBA18A3F3537BE7BF5C796B14D0C02EA9EB39728A0572F9EE</data1><data2>7C8D4EBAB1909E57334C40BCB5E3E1025B6EA9C5879CE2BE4D438D6A2D7080067121DA0E6912245D39317F191597C085C7106D869F352ED352E4935B</data2><sign>13BFAA696D6729362EB059CECE99B354</sign></oosRequestDataResponse></posnetResponse>"

Aradından Aşağıdaki Gibi forum oluşuyor ancak post olmuyor  bu kısıma https://setmpos.ykb.com/3DSWebService/YKBPaymentService anlamadım


"<form id=\"PaymentForm\" name=\"PaymentForm\" action=\"https://setmpos.ykb.com/3DSWebService/YKBPaymentService\" role=\"form\" method=\"POST\"><input type=\"hidden\" name=\"posnetData\" value=\"D41B6A08198CE1D0C3D34D60F60E2B798C3DB49969D9685432311A17BA2016264929462932BF8CFFE41CC18A890AA6EB881E38C917F7B82793438369DA7B96F7E5A64412E0F83A9ADAFA5C795293100FEB4AF80F19C89EFC0790A0C41ED4CF107FA019D85A8F346EEA79B6FF5EDF18879E7BE1CDE3F9298B58DDDC190E5891F76EC5479C311A3531718CD7CEE0995594B9804F6EBA18A3F3537BE7BF5C796B14D0C02EA9EB39728A0572F9EE\"><input type=\"hidden\" name=\"posnetData2\" value=\"7C8D4EBAB1909E57334C40BCB5E3E1025B6EA9C5879CE2BE4D438D6A2D7080067121DA0E6912245D39317F191597C085C7106D869F352ED352E4935B\"><input type=\"hidden\" name=\"digest\" value=\"13BFAA696D6729362EB059CECE99B354\"><input type=\"hidden\" name=\"mid\" value=\"6700972634\"><input type=\"hidden\" name=\"posnetID\" value=\"1010052104940374\"><input type=\"hidden\" name=\"vftCode\" value=\"\"><input type=\"hidden\" name=\"merchantReturnURL\" value=\"http://localhost:15536/Plugins/PaymentThreeDPayment/Callback\"><input type=\"hidden\" name=\"lang\" value=\"tr\"><input type=\"hidden\" name=\"url\" value=\"\"><input type=\"hidden\" name=\"openANewWindow\" value=\"0\"><input type=\"hidden\" name=\"useJokerVadaa\" value=\"1\"></form><script>document.forms[0].submit();</script>"

**Comment by fetullahyldz** [comment]
[HttpPost]
        public async Task<IActionResult> ThreeDGate()    Ben direk post işlemini burdan veriyorum yani sizin indexte verdiğiniz gibi değil buraya direk post işelmini gönderiyorum nopcommerce için yapıyorum bunu herşey iyi ancak post etmiyor

**Comment by fetullahyldz** [comment]
samples/ThreeDPayment.Sample/wwwroot/js/site.js     bu arada burda js var buton post ediyor galiba

**Comment by fetullahyldz** [comment]
> Bende Nop Commerce'e Yapı Kredi için eklenti yazacağım sanırım baya bi uğraşacağız.

Yapı kredi çok uğraştırıyor ip olayında sürekli ip değişiyor sürekli ip ekle diyoruz bekliyoruz karşı taraf doküman gönderiyor oku yap diyor örnek kod yok birde daha önce dll vardı yaptım çalışıyordu sonra güncelleme oldu dll devre dışı  diğer bankalar çok kolay ama yapı kredi problem

**Comment by fetullahyldz** [comment]
ThreeDGatewayRequest   içinde 

 string responseContent = await response.Content.ReadAsStringAsync();  burdan sonra benim post complete düşürüyor ama debug etiğimde devam ediyor nasıl çözeğimi anlamdım bir türlü

**Comment by fetullahyldz** [comment]
string requestXml = $@"<?xml version=""1.0"" encoding=""utf-8""?>
                                        <posnetRequest>
                                            <mid>{merchantId}</mid>
                                            <tid>{terminalId}</tid>
                                            <oosRequestData>
                                                <posnetid>{posnetId}</posnetid>
                                                <XID>{request.OrderNumber}</XID>
                                                <amount>{amount}</amount>
                                                <currencyCode>{currencyCode}</currencyCode>
                                                <installment>{string.Format("{0:00}", request.Installment)}</installment>
                                                <tranType>Sale</tranType>
                                                <cardHolderName>{request.CardHolderName}</cardHolderName>
                                                <ccno>{request.CardNumber}</ccno>
                                                <expDate>{request.ExpireYear}{request.ExpireMonth}</expDate>
                                                <cvc>{request.CvvCode}</cvc>
                                            </oosRequestData>
                                        </posnetRequest>";

                var httpParameters = new Dictionary<string, string>();
                httpParameters.Add("xmldata", requestXml);

                var response = await httpClient.PostAsync(request.BankParameters["verifyUrl"], new FormUrlEncodedContent(httpParameters));
                string responseContent = await response.Content.ReadAsStringAsync();

 
Bu kısımda sonra bitiriyor aceba localde olduğu içinmi tam anlamadım burda xml olarak gidiyor await response.Content.ReadAsStringAsync(); dataları alıp    https://setmpos.ykb.com/3DSWebService/YKBPaymentService  buraya post emem gerekiyor ardından ama dediğim gibi orda bitiryor işlemi

**Comment by sefacan** [comment]
Örnek projeyi yeniledim ve tam olarka çalışır hale getirdim. Tüm aşamaların daha anlaşılır hale geldiğini düşünüyorum.

**Comment by srknhcgl** [comment]
örnek projede kredi kartı yapıştırma javascript ile kapatılmış. test işlemini çok uzattığı için kredi kartı no yapıştırma özelliğini açar mısınız?

**Comment by fetullahyldz** [comment]
Merhaba  c# tarafında oluşturulan forum hiddenlar da hmtl head ve body etiketleri oluşturulamamış javascripleri head kısmında oluşturdum o kısmı geçti ancak localde test için yapı kredi gerçekten problem  testleri gerçek sunucuda yapmamız gerektiğini söylediler.  gerçek ortamda test edeceğim localde https olması lazım bundan dolayıda galiba banka izin vermiyordur. tüm yöntemleri deniyorum

**Comment by sefacan** [comment]
asp.net core ile geliştirme yapıyorsanız local ortamda ssl kullanabilirsiniz. Projeye bazı değişiklikler yaptım yeni örneği incelemenizi öneririm. Yapıkrediyi de test edebilirsniz.

**Comment by fetullahyldz** [comment]
Aslında Şöyle ben bunun nopcommerce uyarladım modül yazdım nopcommerce için nop ta ssl yok  yeni sürümü incliyeyim teşekür ederim
