### ISSUE TITLE
Kredi kartı numarasından banka ve kart tipinin otomatik atanması

### ISSUE THREAD

**Issue by gildedero** [sefacan/3DPaymentAspNetCore#14]
Merhaba, Kart numarasının ilk 6 hanesi ile bankalar ve kart tipi tespit edilebiliyor, geliştirme yapmaya devam ediyorsan böyle bir özellik eklemek için çalışabilirim. [örnek bin listesi](https://gist.githubusercontent.com/berkayunal/1595676/raw/debaa41dfd85d57b7681bcc46341f9bc0fa55682/Kredi%2520Kart%25C4%25B1%2520BIN%2520Listesi%2520-%2520CSV)

**Comment by sefacan** [comment]
Selam,
Örnek projede bayağı bir eksik var hem onların düzeltilmesi hem de bu tarz eksiklerin giderilmesi gerekiyor. Katkı yapmak istersen tabiki pull request gönderebilirsin
