### ISSUE TITLE
Ziraat Bankası

### ISSUE THREAD

**Issue by admcicek** [sefacan/3DPaymentAspNetCore#2]
Merhabalar. Ziraat Bankası için 3d ve 3d gerektirmeyen durumlar için sanal pos entegrasyonu yapmam gerekiyor. Sizin bu çalışma ile ilerleyebilirmiyim.
Şimdiden teşekürler.

**Comment by sefacan** [comment]
Merhaba,

3D kullanıp kullanmayacağını müşteriye kredi kartı formunda opsiyon olarak sunabilirsiniz. Bir checkbox örneğin. Sonrasında Ziraat bankasının size vereceği non-secure işlemlerdeki xml request örneğini kullanarak 3D olmayan işlemlere de izin verebilirsiniz.

İyi günler.

**Comment by admcicek** [comment]
Sizin yaptığınız örnekteki banka seçimi paranın çekileceği bankamı yoksa banka sanal pos'una mı denk geliyor.Biraz yönlendirebilirseniz sevinirim. ziraatle ilgili bir kaç örnek buldum. hatta bankanın kendi örnekleri var ama beğenmedim. .Net Core 3.1 ve Angular TypeScript kullanıyorum. Sizin yazdığınız çok temiz görünüyor. Elinize sağlık.

**Comment by sefacan** [comment]
Yorumunuz için teşekkürler bende olabildiğince basit ve anlaşılır olması için uğraşıyorum.

Yaptığım örnekteki ödeme formunda hangi sanal pos entegrasyonu ile ödeme yapılacağı seçiliyor. Daha kapsamlı projelerde bu işlemi kartın ilk 6 hanesi yani bin numarasıyla otomatik belirleyebiliyorsunuz. 
* Diyelim ki elinizde 4 banka ile sanal pos entegrasyonu mevcut. Bunlar garanti, ziraat, iş bankası ve finansbank olsun.
* Bunlar arasından birini varsayılan banka olarak belirleyin.
* Veritabanınızda bankalarla ilişkilendirilmiş şekilde ilgili bankaların bin numaraları kayıtlı olsun.
* Müşteri ödeme için kart bilgisi girdiğinde 6. haneden sonra veritabanınızdan bin numarasıyla ilişkili bankayı bulun. Kartın bankası sizin 4 entegrasyonunuz arasından biri ise o sanal pos ile ödeme yaptırın.
* Eğer müşteri, elinizdeki 4 banka dışında bir bankanın kredi kartıyla ödeme yapıyorsa varsayılan olarak belirlediğiniz sanal posa yönlendirin. 

Bu şekilde müşterinize banka seçtirmek zorunda kalmaz ve bankalara daha az komisyon ödersiniz.
* Örneğin elinizde garanti bankası entegrasyonu varken garanti kredi kartı ile ödeme yapacak bir müşterinin işlemini işbank sanal posundan geçerseniz hem taksit yapamazsınız hem komisyon oranları değişiklik gösterebilir.

İyi günler.

**Comment by admcicek** [comment]
Çok teşekür ederim Sefa bey.
