### ISSUE TITLE
3D Secure doğrulamasından sonra "00" kodu dönüyor ama success false

### ISSUE THREAD

**Issue by lumixus** [sefacan/3DPaymentAspNetCore#20]
Selamlar,
.net Core 3.1 ile proje geliştiriyordum 3d secure sayfasından sonra "00" kodu dönüyor approved mesajı ile ama success değeri "false" sebebi ne olabilir ? Nestpay ile test ediyorum.

**Comment by sefacan** [comment]
Hangi bankayi kullanıyorsunuz?

**Comment by lumixus** [comment]
İşbankası

**Comment by sefacan** [comment]
[NestPayPaymentProvider.cs#L85](https://github.com/sefacan/3DPayment/blob/fc073c2046f7acd5e220cc4e13b2dcf60d9abb7b/src/ThreeDPayment/Providers/NestPayPaymentProvider.cs#L85) işlem sonucunu buradaki gibi kontrol etmelisiniz.

**Comment by lumixus** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/44450220/103032133-60f11c80-4570-11eb-9744-a392a56f68a8.png)
Burada o fonksiyonu kullanıyorum sanırım.

**Comment by sefacan** [comment]
Ama IFormCollection dışında herhangi bir değer göndermiyorsun.

**Comment by lumixus** [comment]
VerifyGatewayResult içini doldurarak yolladım fonksiyona ama "not authenticated" hatası döndürdü bu sefer hiç 3d kodu istemeden.

**Comment by sefacan** [comment]
Gönderdiğiniz bilgilerde bir yanlış olabilir. Debug ederek gönderilen bilgilerin doğruluğunu kontrol edin.

**Comment by lumixus** [comment]
Tekrardan bilgileri kontrol edip düzenledim bu sefer 3d doğrulama ekranını geçtim fakat aldığım response şu şekilde. Çok ilginç bir şekilde Error code "00" başarılı anlamına geliyor. "Approved" ve "Authenticated" mesajını da alıyorum ama success değeri false.
![Screenshot_3](https://user-images.githubusercontent.com/44450220/103151405-ece08f80-478e-11eb-8622-3c7e83876bcd.png)

**Comment by lumixus** [comment]
Şöyle bir durum var nestpayin entegrasyon dökümanını kontrol ettiğimde "processType" keyi "islemtipi" olarak  gözüküyor acaba bu yüzden sorun oluyor olabilir mi ? Form da processtype olarak post ediyoruz.
