### ISSUE TITLE
KuveytTurk entegrasyon hk.

### ISSUE THREAD

**Issue by mesutdede** [sefacan/3DPaymentAspNetCore#22]
Merhaba,

Kuveyt Turk entegrasyonu sırasında tarayıcı console unda "Refused to display 'https://www.nsoftware.com/3dsecure/testing/acs.asp' in a frame because it set 'X-Frame-Options' to 'deny'" hatası aldım. Bunun üzerine Startup.cs e aşağıdaki kodu ekledim.

app.Use(async (context, next) =>
{
    context.Response.Headers.Add("X-Frame-Options", "DENY");
    await next();
});

Bundan sonra yaptığım denemede ise "Payment:1 Refused to display 'https://localhost:44361/payment/confirm/4459f714-786f-4cf6-8b7a-dffc19e7bcdb' in a frame because it set 'X-Frame-Options' to 'deny'." hatasını aldım. Bununla ilgili bir çözüm öneriniz var mıdır?

**Comment by sefacan** [comment]
Merhaba,
Repoda kuveytturk ve Finansbank henüz test edilmedi. 
Aldığınız hatayı daha önce bir kişi daha bildirdi ve kuveytturk ile görüştüğünde sanal posun iframe içerisinde kullanılmasına izin verilmediğini söylediler. Zaten aldığınız hata iframe kullanımı engellediği için oluyor. Bu yüzden modal açmak yerine sayfa yönlendirme yapmanız gerekmekte.
Uygulama response headera ek bir parametre eklemeniz sorunu çözmeyecek çünkü sorun banka tarafında oluşuyor kendi uygulamanız tarafında değil.

**Comment by mesutdede** [comment]
Merhaba,

Dönüş için teşekkür ederim. Anlaşıldı. Sayfa yönlendirme ile halledeceğiz. Tekrar teşekkür ederim.
