### ISSUE TITLE
POSNET 3D Secure Kontrolü

### ISSUE THREAD

**Issue by emrests** [sefacan/3DPaymentAspNetCore#25]
Merhaba,

Özellikle factory yapısı çok başarılı olmuş. Benzer bir proje yapmışken farklı neler yapılabilir araştırmamın sonucunda denk geldim. Factory yapısını kendi projemde kullanacağım. Teşekkürler çalışma için.

Bir kontrol bildirmek isterim. 

POSNET için posnetResponse/approved olması tek başına yeterli değil. Bu işlemin kabul edilip edilmediği bilgisini veriyor. Fakat 3D Secure ile yapılan bir işlem olup olmadığını vermiyor. Bu da 3D secure olmadan işlem yapılabilmesine neden oluyor Half Secure olarak adlandırılıyor. 

Eğer sistem içerisinde 3D Secure kullanılması şartı istenirse (bence kart hırsızlığı için istenmeli) mdStatus alanındaki değerin 1 olmasının kontrol edilmesi gerekli. Eğer bir değilse işleme onay verilmemeli.

**Comment by sefacan** [comment]
Selamlar bu yönde bir geliştirme yapıp katkıda bulunabilirsiniz.
