### ISSUE TITLE
TestParameters Null Geliyor

### ISSUE THREAD

**Issue by areltasarim** [sefacan/3DPaymentAspNetCore#26]
Merhaba

VakifbankPaymentProvider.cs  dosyasında  vakıfbankın sanalpos bilgilerini ekledim ancak  TestParameters  null olarak geliyor yardımcı olurmusunuz

**Comment by sefacan** [comment]
Selamlar
TestParameters kendi projenizde aşağıdaki şekilde olması gerek.
https://github.com/sefacan/3DPayment/blob/3625e11bbd4564897220c56f9525813851794ea4/src/ThreeDPayment/Providers/VakifbankPaymentProvider.cs#L349

**Comment by areltasarim** [comment]
hocam dediğiniz gibi yaptım merchant id kısmınada kendi bilgilerimi yazdım ödeme kısmında İşlem sırasında bir hata oluştu. uyarısı alıyorum
