### ISSUE TITLE
Ziraat Bankası

### ISSUE THREAD

**Issue by omerrciftcii** [sefacan/3DPaymentAspNetCore#28]
Merhaba, ziraat entegrasyonunu göremedim var mı bir geliştirme?

**Comment by sefacan** [comment]
Selamlar,

https://github.com/sefacan/3DPayment/blob/master/src/ThreeDPayment/Providers/NestPayPaymentProvider.cs buradaki dosya bir çok bankada ortak. Ziraat Bankası da bu yapı ile çalışıyor.

**Comment by omerrciftcii** [comment]
Teşekkür ederim, elinize sağlık
