### ISSUE TITLE
KuvetTurk CancelRequest

### ISSUE THREAD

**Issue by emrakin** [sefacan/3DPaymentAspNetCore#29]
Bir projede bu kısımda takıldım nasıl ilerleyeceğimi tam kestiremedim. KuveytTurk entegrasyonunda CancelRequest kısmını entegre edecek misin?

**Comment by sefacan** [comment]
Merhaba, yakın zamanda bu geliştirmeyi yapacak fırsat bulamayacağım. Dokümanları inceleyip xml örneklerine ve githubdaki diğer kuveytturk sanal pos örneklerine bakarak geliştirmeyi yapabilirsin. Aynı zamanda buraya da pull request açarak projeye katkıda bulunabilirsin.
