### ISSUE TITLE
Sample da eksiklikler hk.

### ISSUE THREAD

**Issue by suatsuphi** [sefacan/3DPaymentAspNetCore#3]
Merhaba,

Hocam ThreeDPayment.Sample projede eksikler var. Örneğin ThreeDGate.cshtml sayfası eksik yönlendirme sayfaları Callback vb... proje bitmiş gibi duruyor. 
Bunları ne zaman eklersiniz. 

Birde sormak istediğim bir soru var. Kredi kartından bağlı olduğunu bankayı belirleyip, o bankanın sanal postuna yok ise varsayılan sanal posta yönlendirmeyi nasıl yaparız ? 

Proje harika olmuş elinize sağlık...

**Comment by sefacan** [comment]
Merhaba,
Bu konuda bir PR çalışması yapabilirsen eksiklerin giderilmesine katkı sağlayabilirsin. 
Aynı şekilde ben de geliştirmelere devam edeceğim.
