### ISSUE TITLE
yeni finans bank test ve canlı ortam 3dgate adresi

### ISSUE THREAD

**Issue by suatsuphi** [sefacan/3DPaymentAspNetCore#7]
Merhaba,
Hocam url finansbank için url adresi nedir ? 
parameterResult.PaymentUrl = new Uri("https://finansbank.com");

**Comment by sefacan** [comment]
Selam,
Aşağıdaki adresleri kullanabilirsiniz.

Test - https://vpostest.qnbfinansbank.com/Gateway/Default.aspx
Canlı - https://vpos.qnbfinansbank.com/Gateway/Default.aspx
