### ISSUE TITLE
"Error - Guvenlik Kodu hatali."

### ISSUE THREAD

**Issue by HaciTakkimGitHub** [sefacan/3DPaymentAspNetCore#8]
Merhaba,

Kodları çalıştırığımda 3d syafasına gitmiyor. Doğrudan callback metoduna erişiyor. Sonrasında ise PaymentResult nesnesinde "Error - Guvenlik Kodu hatali." hatası alıyorum. Bu konuda bir fikriniz var mıdır ?

Yardımlarınız için teşekkürler.

**Comment by sefacan** [comment]
Merhaba,
Aldığınız hata kullandığınız kredi kartının arkasındaki 3 haneli güvenlik kodunun hatalı olduğu anlamına geliyor.

İyi günler.

**Comment by suatsuphi** [comment]
Her banka için o bankanın kredi kartı kullanılmalı yoksa genel bir hata alınıyor. 
burada test kartları listesi mevcut.
[https://payfull.com/api-docs/en/test-cards](url)
hocam ne zaman tamamlayacaksınız projeyi ? teşekkürler
